apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcareapp-deploy
  labels:
    app: healthcareapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcareapp
  template:
    metadata:
      labels:
        app: healthcareapp
    spec:
      containers:
      - name: healthcareapp-container
        image: revati21/healthcare-app
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: healthcareapp-np-service
  labels:
    app: healthcareapp
spec:
  selector:
    app: healthcareapp
  type: NodePort
  ports:
  - nodePort: 31031  
    port: 8083
    targetPort: 8083
