apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcareapp-deploy
  labels:
    app: healthcareapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcareapp
  template:
    metadata:
      labels:
        app: healthcareapp
    spec:
      containers:
      - name: healthcareapp-container
        image: revati21/healthcare-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082  # Change this from 8083 to 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcareapp-np-service
  labels:
    app: healthcareapp
spec:
  selector:
    app: healthcareapp
  type: NodePort
  ports:
  - protocol: TCP
    port: 8082           
    targetPort: 8082      
    nodePort: 31031
