apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcareapp-deploy
  labels:
    app: healthcareapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcareapp
  template:
    metadata:
      labels:
        app: healthcareapp
    spec:
      containers:
      - name: healthcareapp-container
        image: revati21/healthcare-app:latest  # Ensure latest image is used
        imagePullPolicy: Always  # Force Kubernetes to pull the latest image
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: healthcareapp-np-service
  labels:
    app: healthcareapp
spec:
  selector:
    app: healthcareapp
  type: NodePort
  ports:
  - protocol: TCP
    port: 8083           # Service port
    targetPort: 8083      # Container port
    nodePort: 31031       # Exposed NodePort (should be 30000–32767)
